//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionResultExample.CalculatorServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalculatorServiceReference.CalculatorServiceSoap")]
    public interface CalculatorServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ActionResultExample.CalculatorServiceReference.HelloWorldResponse HelloWorld(ActionResultExample.CalculatorServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ActionResultExample.CalculatorServiceReference.HelloWorldResponse> HelloWorldAsync(ActionResultExample.CalculatorServiceReference.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name oper from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddCalculator", ReplyAction="*")]
        ActionResultExample.CalculatorServiceReference.AddCalculatorResponse AddCalculator(ActionResultExample.CalculatorServiceReference.AddCalculatorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddCalculator", ReplyAction="*")]
        System.Threading.Tasks.Task<ActionResultExample.CalculatorServiceReference.AddCalculatorResponse> AddCalculatorAsync(ActionResultExample.CalculatorServiceReference.AddCalculatorRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ActionResultExample.CalculatorServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ActionResultExample.CalculatorServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ActionResultExample.CalculatorServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ActionResultExample.CalculatorServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddCalculatorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddCalculator", Namespace="http://tempuri.org/", Order=0)]
        public ActionResultExample.CalculatorServiceReference.AddCalculatorRequestBody Body;
        
        public AddCalculatorRequest() {
        }
        
        public AddCalculatorRequest(ActionResultExample.CalculatorServiceReference.AddCalculatorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddCalculatorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int a;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int b;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string oper;
        
        public AddCalculatorRequestBody() {
        }
        
        public AddCalculatorRequestBody(int a, int b, string oper) {
            this.a = a;
            this.b = b;
            this.oper = oper;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddCalculatorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddCalculatorResponse", Namespace="http://tempuri.org/", Order=0)]
        public ActionResultExample.CalculatorServiceReference.AddCalculatorResponseBody Body;
        
        public AddCalculatorResponse() {
        }
        
        public AddCalculatorResponse(ActionResultExample.CalculatorServiceReference.AddCalculatorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddCalculatorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddCalculatorResult;
        
        public AddCalculatorResponseBody() {
        }
        
        public AddCalculatorResponseBody(string AddCalculatorResult) {
            this.AddCalculatorResult = AddCalculatorResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalculatorServiceSoapChannel : ActionResultExample.CalculatorServiceReference.CalculatorServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorServiceSoapClient : System.ServiceModel.ClientBase<ActionResultExample.CalculatorServiceReference.CalculatorServiceSoap>, ActionResultExample.CalculatorServiceReference.CalculatorServiceSoap {
        
        public CalculatorServiceSoapClient() {
        }
        
        public CalculatorServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ActionResultExample.CalculatorServiceReference.HelloWorldResponse ActionResultExample.CalculatorServiceReference.CalculatorServiceSoap.HelloWorld(ActionResultExample.CalculatorServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ActionResultExample.CalculatorServiceReference.HelloWorldRequest inValue = new ActionResultExample.CalculatorServiceReference.HelloWorldRequest();
            inValue.Body = new ActionResultExample.CalculatorServiceReference.HelloWorldRequestBody();
            ActionResultExample.CalculatorServiceReference.HelloWorldResponse retVal = ((ActionResultExample.CalculatorServiceReference.CalculatorServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ActionResultExample.CalculatorServiceReference.HelloWorldResponse> ActionResultExample.CalculatorServiceReference.CalculatorServiceSoap.HelloWorldAsync(ActionResultExample.CalculatorServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ActionResultExample.CalculatorServiceReference.HelloWorldResponse> HelloWorldAsync() {
            ActionResultExample.CalculatorServiceReference.HelloWorldRequest inValue = new ActionResultExample.CalculatorServiceReference.HelloWorldRequest();
            inValue.Body = new ActionResultExample.CalculatorServiceReference.HelloWorldRequestBody();
            return ((ActionResultExample.CalculatorServiceReference.CalculatorServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ActionResultExample.CalculatorServiceReference.AddCalculatorResponse ActionResultExample.CalculatorServiceReference.CalculatorServiceSoap.AddCalculator(ActionResultExample.CalculatorServiceReference.AddCalculatorRequest request) {
            return base.Channel.AddCalculator(request);
        }
        
        public string AddCalculator(int a, int b, string oper) {
            ActionResultExample.CalculatorServiceReference.AddCalculatorRequest inValue = new ActionResultExample.CalculatorServiceReference.AddCalculatorRequest();
            inValue.Body = new ActionResultExample.CalculatorServiceReference.AddCalculatorRequestBody();
            inValue.Body.a = a;
            inValue.Body.b = b;
            inValue.Body.oper = oper;
            ActionResultExample.CalculatorServiceReference.AddCalculatorResponse retVal = ((ActionResultExample.CalculatorServiceReference.CalculatorServiceSoap)(this)).AddCalculator(inValue);
            return retVal.Body.AddCalculatorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ActionResultExample.CalculatorServiceReference.AddCalculatorResponse> ActionResultExample.CalculatorServiceReference.CalculatorServiceSoap.AddCalculatorAsync(ActionResultExample.CalculatorServiceReference.AddCalculatorRequest request) {
            return base.Channel.AddCalculatorAsync(request);
        }
        
        public System.Threading.Tasks.Task<ActionResultExample.CalculatorServiceReference.AddCalculatorResponse> AddCalculatorAsync(int a, int b, string oper) {
            ActionResultExample.CalculatorServiceReference.AddCalculatorRequest inValue = new ActionResultExample.CalculatorServiceReference.AddCalculatorRequest();
            inValue.Body = new ActionResultExample.CalculatorServiceReference.AddCalculatorRequestBody();
            inValue.Body.a = a;
            inValue.Body.b = b;
            inValue.Body.oper = oper;
            return ((ActionResultExample.CalculatorServiceReference.CalculatorServiceSoap)(this)).AddCalculatorAsync(inValue);
        }
    }
}
